Repository LuckyDay-project/LuckyDay-FE, pull requests merged in 2024-10, with the labels that each got.

#216 Refactor/#214 디자인 시스템 및 레이아웃 개선
  src/assets/icon/ic_menu.svg
  src/components/common/buttons/svgButton/SvgButton.styled.ts
  src/components/common/buttons/svgButton/SvgButton.tsx
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/Layout.tsx
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/footer/Footer.styled.ts
  src/components/common/layout/footer/Footer.tsx
  src/components/common/layout/footer/index.ts
  src/components/common/layout/header/Header.styled.ts
  src/components/common/layout/logo/Logo.styled.ts
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/common/layout/navigationToggle/sendFeedbackModal/SendFeedbackModal.styled.ts
  src/components/common/modal/confirmModal/ConfirmModal.styled.ts
  src/components/domain/landing/carousel/Carousel.styled.ts
  src/components/domain/luckyBoard/archiveModal/ArchiveModal.styled.ts
  src/components/domain/luckyBoard/createAlertModal/CreateAlertModal.styled.ts
  src/components/domain/luckyBoard/createLuckyDayButton/CreateLuckyDayButton.styled.ts
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.styled.ts
  src/components/domain/myPage/editProfileConfirmModal/EditProfileConfirmModal.styled.ts
  src/components/domain/reviewLuckyDay/deleteReviewConfirmModal/DeleteReviewConfirmModal.styled.ts
  src/pages/404/Error404Page.styled.ts
  src/pages/landing/LandingPage.styled.ts
  src/pages/loading/LoadingPage.styled.ts
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.styled.ts
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.tsx
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.styled.ts
  src/pages/myPage/myPage.styled.ts
  src/pages/noticeBoard/NoticeBoardPage.styled.ts
  src/pages/noticeDetail/NoticeDetailPage.styled.ts
  src/pages/noticeList/NoticeListPage.styled.ts
  src/pages/profile/ProfilePage.styled.ts
  src/pages/profile/ProfilePage.tsx
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.styled.ts
  src/pages/viewLuckyDay/ViewLuckyDayPage.styled.ts
  src/styles/globalStyle.ts
  src/styles/themes/fonts.ts
Labels: REFACTOR, STYLE

#218 Feat/#201 튜토리얼 공용 컴포넌트 및 레이아웃 제작
  src/App.tsx
  src/components/common/layout/Layout.tsx
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/common/layout/navigationToggle/sendFeedbackMessage/SendFeedbackMessage.tsx
  src/components/domain/landing/index.ts
  src/components/domain/landing/kakaoLogin/KakaoLogin.tsx
  src/components/domain/landing/tutorialStartButton/tutorialStartButton.tsx
  src/components/domain/luckyBoard/countLuckyDayModal/CountLuckyDayModal.tsx
  src/components/index.ts
  src/components/tutorial/container/closeTutorialConfirmModal/CloseTutorialConfirmModal.styled.ts
  src/components/tutorial/container/closeTutorialConfirmModal/CloseTutorialConfirmModal.tsx
  src/components/tutorial/container/index.ts
  src/components/tutorial/container/logoTooltip/LogoTooltip.styled.ts
  src/components/tutorial/container/logoTooltip/LogoTooltip.tsx
  src/components/tutorial/container/tutorialTextBox/TutorialTextBox.styled.ts
  src/components/tutorial/container/tutorialTextBox/TutorialTextBox.tsx
  src/components/tutorial/context/TutorialContext.tsx
  src/components/tutorial/context/index.ts
  src/components/tutorial/hooks/index.ts
  src/components/tutorial/hooks/useTutorial.ts
  src/components/tutorial/index.ts
  src/components/tutorial/layout/TutorialLayout.styled.ts
  src/components/tutorial/layout/TutorialLayout.tsx
  src/components/tutorial/layout/index.ts
  src/components/tutorial/steps/00_welcome/Welcome.tsx
  src/components/tutorial/steps/01_createCycle/01_beforeBoard/BeforeBoard.styled.ts
  src/components/tutorial/steps/01_createCycle/01_beforeBoard/BeforeBoard.tsx
  src/components/tutorial/steps/03_finish/Finish.styled.ts
  src/components/tutorial/steps/03_finish/Finish.tsx
  src/components/tutorial/steps/StepWrapper.tsx
  src/components/tutorial/steps/index.ts
  src/components/tutorial/steps/tutorialSteps.ts
  src/components/tutorial/steps/tutorialTexts.ts
  src/pages/index.ts
  src/pages/landing/LandingPage.tsx
  src/pages/tutorial/TutorialPage.styled.ts
  src/pages/tutorial/TutorialPage.tsx
  src/types/common/common.ts
  src/types/common/index.ts
  src/types/index.ts
  src/types/tutorial/index.ts
  src/types/tutorial/tutorial.ts
Labels: FEAT

#220 Fix/#219 tutorial, layout 누락 코드 반영
  .yarn/install-state.gz
  src/components/common/layout/Layout.tsx
Labels: FIX

#223 Feat/#211 튜토리얼 step 초기 세팅 추가
  package.json
  src/components/tutorial/steps/01_createCycle/02_selectActivity/SelectActivity.tsx
  src/components/tutorial/steps/01_createCycle/03_setDate/SetDate.tsx
  src/components/tutorial/steps/01_createCycle/04_setNumber/SetNumber.tsx
  src/components/tutorial/steps/01_createCycle/05_exceptDate/ExceptDate.tsx
  src/components/tutorial/steps/01_createCycle/06_confirm/Confirm.tsx
  yarn.lock
Labels: FEAT

#225 Feat/#224 버튼레이아웃 및 럭키데이생성 css 수정
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/buttonLayout/ButtonLayout.tsx
  src/components/domain/createLuckyDay/container/calendar/Calendar.styled.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.styled.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.styled.ts
  src/components/domain/createLuckyDay/selectCount/SelectCount.styled.ts
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.styled.ts
Labels: FEAT, STYLE
