Repository LuckyDay-project/LuckyDay-FE, pull requests merged in 2024-09, with the labels that each got.

#200 Style/#199 아카이브 모달 인터렉션 추가 및 리팩토링
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/domain/luckyBoard/archiveModal/ArchiveModal.styled.ts
  src/components/domain/luckyBoard/archiveModal/ArchiveModal.tsx
  src/components/domain/luckyBoard/archiveModal/hooks/index.ts
  src/components/domain/luckyBoard/archiveModal/hooks/useVisibility.ts
  src/components/domain/luckyBoard/createLuckyDayButton/CreateLuckyDayButton.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
Labels: REFACTOR, STYLE

#206 Feat/#202 pwa 세팅
  .yarn/install-state.gz
  index.html
  package.json
  public/favicon.ico
  public/images/icons/icon_144.png
  public/images/icons/icon_152.png
  public/images/icons/icon_180.png
  public/images/icons/icon_192.png
  public/images/icons/icon_48.png
  public/images/icons/icon_512.png
  public/images/icons/icon_72.png
  public/images/icons/icon_96.png
  public/images/logo/logo_square_180.png
  public/images/logo/logo_square_192.png
  public/manifest.json
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
  vite.config.ts
  yarn.lock
Labels: FEAT

#208 Fix/#207 빌드 에러 수정
  .yarn/install-state.gz
  package.json
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  vite.config.ts
  yarn.lock
Labels: FIX

#213 Fix/#212 동일 이미지 재업로드 오류 수정
  src/components/common/layout/navigationToggle/sendFeedbackModal/SendFeedbackModal.tsx
  src/components/common/svgFrame/centeredSvgFrame/centeredSvgFrame.tsx
  src/components/domain/luckyBoard/countLuckyDayModal/CountLuckyDayModal.tsx
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.tsx
  src/components/domain/myPage/editProfileConfirmModal/EditProfileConfirmModal.tsx
  src/components/domain/reviewLuckyDay/fileUploader/FileUploader.tsx
Labels: FIX
