Repository LuckyDay-project/LuckyDay-FE, pull requests merged in 2024-05, with the labels that each got.

#21 Feat/#19 럭키보드 신규회원 UI 제작
  src/assets/icon/ic_empty.png
  src/assets/icon/ic_empty_beige.png
  src/assets/icon/ic_plus.svg
  src/assets/icon/index.ts
  src/assets/icon/next.png
  src/assets/icon/prev.png
  src/assets/machine-empty.png
  src/assets/machine-filled.png
  src/components/common/carousel/Carousel.styled.ts
  src/components/common/carousel/Carousel.tsx
  src/components/common/createLuckyDayButton/CreateLuckyDayButton.styled.ts
  src/components/common/createLuckyDayButton/CreateLuckyDayButton.tsx
  src/components/common/createLuckyDayButton/index.ts
  src/components/common/homeButton/HomeButton.tsx
  src/components/common/index.ts
  src/pages/404/Error404Page.styled.ts
  src/pages/404/Error404Page.tsx
  src/pages/index.ts
  src/pages/landing/Landing.styled.ts
  src/pages/landing/Landing.tsx
  src/pages/landing/LandingPage.styled.ts
  src/pages/landing/LandingPage.tsx
  src/pages/luckyBoard/LuckyBoardPage.styled.ts
  src/pages/luckyBoard/LuckyBoardPage.tsx
  src/router/Router.tsx
Labels: FEAT

#22 Feat/#16 럭키데이 생성 스크린 제작
  public/images/empty.png
  public/images/img_medium_beige.png
  public/images/img_medium_orange.png
  public/images/img_small.png
  public/images/img_toggle.png
  src/assets/icon/ic_book.svg
  src/assets/icon/ic_candy.svg
  src/assets/icon/ic_heart.svg
  src/assets/icon/ic_present.svg
  src/assets/icon/ic_shoe.svg
  src/assets/icon/ic_smile.svg
  src/assets/icon/index.ts
  src/components/common/calendar/Calendar.tsx
  src/components/common/index.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.styled.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.tsx
  src/components/domain/createLuckyDay/container/calendar/hooks/useCalendar.ts
  src/components/domain/createLuckyDay/container/calendar/index.ts
  src/components/domain/createLuckyDay/container/index.ts
  src/components/domain/createLuckyDay/container/progressBar/ProgressBar.styled.ts
  src/components/domain/createLuckyDay/container/progressBar/ProgressBar.tsx
  src/components/domain/createLuckyDay/container/progressBar/index.ts
  src/components/domain/createLuckyDay/index.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.styled.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.tsx
  src/components/domain/createLuckyDay/selectCount/SelectCount.styled.ts
  src/components/domain/createLuckyDay/selectCount/SelectCount.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.styled.ts
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.styled.ts
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.tsx
  src/components/domain/index.ts
  src/components/index.ts
  src/pages/createLuckyDay/CreateLuckyDayPage.styled.ts
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/pages/index.ts
  src/router/Router.tsx
Labels: FEAT

#25 Feat/#20 layout 수정
  public/images/img_small_beige.png
  public/images/img_small_orange.png
  src/App.tsx
  src/components/common/Layout/Layout.styled.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/Layout/buttonLayout/ButtonLayout.tsx
  src/components/common/Layout/buttonLayout/index.ts
  src/components/common/Layout/index.ts
  src/components/common/index.ts
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/Layout.tsx
  src/components/common/layout/index.ts
  src/pages/createLuckyDay/CreateLuckyDayPage.styled.ts
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/router/Router.tsx
  src/styles/globalStyle.ts
Labels: FEAT

#26 Feat/#23 toggle 컴포넌트생성 및 api연동
  .gitignore
  public/images/img_small_square.png
  src/apis/axios.ts
  src/apis/createLuckyDay.ts
  src/apis/index.ts
  src/assets/icon/ic_check.svg
  src/assets/icon/index.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.styled.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.styled.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/index.ts
  src/components/domain/createLuckyDay/selectActivity/container/index.ts
  src/services/createLuckyDay.ts
  src/services/index.ts
Labels: FEAT

#30 Feat/#29 progressbar 컴포넌트 생성
  .yarn/install-state.gz
  src/components/domain/createLuckyDay/container/progressBar/ProgressBar.styled.ts
  src/components/domain/createLuckyDay/container/progressBar/ProgressBar.tsx
  src/styles/themes/colors.ts
Labels: FEAT

#32 Feat/#31 모달 생성
  index.html
  src/App.tsx
  src/assets/icon/ic_close.svg
  src/assets/icon/index.ts
  src/atoms/comon.ts
  src/atoms/index.ts
  src/components/common/index.ts
  src/components/common/modal/Modal.styled.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/baseModal/BaseModal.styled.ts
  src/components/common/modal/baseModal/BaseModal.tsx
  src/components/common/modal/baseModal/index.ts
  src/components/common/modal/confirmModal/ConfirmModal.styled.ts
  src/components/common/modal/confirmModal/ConfirmModal.tsx
  src/components/common/modal/confirmModal/index.ts
  src/components/common/modal/index.ts
  src/components/common/portal/ModalPortal.tsx
  src/components/common/portal/index.ts
  src/hooks/index.ts
  src/hooks/useModal.ts
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/pages/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.styled.ts
  src/pages/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/pages/createLuckyDay/container/createLuckyDayModal/index.ts
  src/pages/createLuckyDay/container/index.ts
Labels: FEAT

#40 Feat/#39 로그인 token 관리 로직 수정
  .yarn/install-state.gz
  package.json
  src/atoms/comon.ts
  src/pages/auth/Auth.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/profile/Profile.tsx
  yarn.lock
Labels: FEAT

#38 Feat/#35 마이페이지 UI 제작
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/pages/index.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.styled.ts
  src/pages/settingLuckyBoard/SettingLuckyBoardPage.styled.ts
  src/pages/settingLuckyBoard/SettingLuckyBoardPage.tsx
  src/router/Router.tsx
Labels: FEAT

#45 Feat/#44 프로필 설정 페이지 UI 제작
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/pages/editProfile/EditProfilePage.styled.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/index.ts
  src/pages/luckyDayArchive/LuckyDayArchivePage.styled.ts
  src/pages/luckyDayArchive/LuckyDayArchivePage.tsx
  src/pages/myPage/MyPage.tsx
  src/router/Router.tsx
Labels: FEAT

#43 Feat/#42 axios interceptor 설정
  .yarn/install-state.gz
  package.json
  src/apis/axios.ts
  src/components/domain/landing/kakaoLogin/KakaoLogin.tsx
  src/config/index.ts
  src/pages/auth/Auth.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/profile/Profile.tsx
  yarn.lock
Labels: FEAT

#37 Feat/#33 svg 컴포넌트 제작
  src/assets/icon/ic_circleBox.svg
  src/assets/icon/ic_largeBox.svg
  src/assets/icon/ic_longBox.svg
  src/assets/icon/ic_mediumBox.svg
  src/assets/icon/ic_shortBox.svg
  src/assets/icon/index.ts
  src/components/common/index.ts
  src/components/common/svgFrame/SvgFrame.styled.ts
  src/components/common/svgFrame/SvgFrame.tsx
  src/components/common/svgFrame/index.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.styled.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.tsx
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
Labels: FEAT

#48 Feat/#46 user context 생성
  index.html
  src/App.tsx
  src/apis/axios.ts
  src/contexts/UserContext.tsx
  src/hooks/index.ts
  src/hooks/useUser.ts
  src/pages/auth/Auth.tsx
  src/pages/profile/Profile.tsx
Labels: FEAT

#50 Feat/#34 users data header 연결
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/contexts/UserContext.tsx
Labels: FEAT

#51 Feat/#47 토스트 컴포넌트 제작
  src/App.tsx
  src/atoms/comon.ts
  src/components/common/index.ts
  src/components/common/toast/Toast.styled.ts
  src/components/common/toast/Toast.tsx
  src/components/common/toast/index.ts
  src/components/common/toast/toastItem/ToastItem.styled.ts
  src/components/common/toast/toastItem/ToastItem.tsx
  src/components/common/toast/toastItem/index.ts
  src/hooks/index.ts
  src/hooks/useToast.ts
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/types/common.ts
  src/types/index.ts
Labels: FEAT

#53 Feat/#41 럭키데이 활동목록 조회 기능 수정
  public/images/img_empty_longBox.png
  public/images/img_empty_mediumBox.png
  public/images/img_toggle.png
  src/apis/createLuckyDay.ts
  src/assets/icon/ic_arrow.svg
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.styled.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.styled.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.tsx
  src/types/domain/createLuckyDay.ts
  src/types/domain/index.ts
  src/types/index.ts
Labels: FEAT

#55 Feat/#52 기존 회원 럭키보드 스크린 제작
  public/images/face-01.png
  src/components/common/createLuckyDayButton/index.ts
  src/components/common/index.ts
  src/components/common/svgFrame/centeredSvgFrame/centeredSvgFrame.styled.ts
  src/components/common/svgFrame/centeredSvgFrame/centeredSvgFrame.tsx
  src/components/common/svgFrame/index.ts
  src/components/domain/luckyBoard/createLuckyDayButton/CreateLuckyDayButton.styled.ts
  src/components/domain/luckyBoard/createLuckyDayButton/CreateLuckyDayButton.tsx
  src/components/domain/luckyBoard/index.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.styled.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/pages/index.ts
  src/pages/luckyBoard/LuckyBoardPage.tsx
  src/pages/luckyBoard/index.ts
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.tsx
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.styled.ts
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.tsx
  src/router/Router.tsx
  src/styles/themes/colors.ts
  src/utils/date.ts
Labels: FEAT

#57 Feat/#49 로그아웃 api 연동
  src/apis/axios.ts
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/contexts/UserContext.tsx
  src/pages/editProfile/EditProfilePage.styled.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/index.ts
  src/pages/luckyDayArchive/LuckyDayArchivePage.styled.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.styled.ts
  src/pages/settingLuckyBoard/SettingLuckyBoardPage.styled.ts
  src/pages/settingLuckyBoard/SettingLuckyBoardPage.tsx
  src/router/Router.tsx
  src/types/declare/types.d.ts
Labels: FEAT

#56 Feat/#54 럭키데이 생성 기능 추가
  src/apis/createLuckyDay.ts
  src/assets/icon/ic_minus.svg
  src/assets/icon/ic_plus.svg
  src/assets/icon/index.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/confirmModal/ConfirmModal.styled.ts
  src/components/common/modal/confirmModal/ConfirmModal.tsx
  src/components/common/svgFrame/SvgFrame.styled.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.styled.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.tsx
  src/components/domain/createLuckyDay/container/calendar/hooks/useCalendar.ts
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.styled.ts
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/components/domain/createLuckyDay/container/createLuckyDayModal/index.ts
  src/components/domain/createLuckyDay/container/index.ts
  src/components/domain/createLuckyDay/container/progressBar/ProgressBar.tsx
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.styled.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.tsx
  src/components/domain/createLuckyDay/selectCount/SelectCount.styled.ts
  src/components/domain/createLuckyDay/selectCount/SelectCount.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.styled.ts
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.styled.ts
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.tsx
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/pages/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.styled.ts
  src/pages/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/pages/createLuckyDay/container/index.ts
  src/services/createLuckyDay.ts
  src/types/domain/createLuckyDay.ts
Labels: FEAT

#63 Feat/#62 럭키보드 아카이브 컴포넌트 제작
  public/images/profile/profile-07.png
  src/components/common/modal/archiveModal/ArchiveModal.styled.ts
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/components/common/modal/archiveModal/index.ts
  src/components/common/modal/index.ts
  src/pages/luckyBoard/LuckyBoardPage.styled.ts
  src/pages/luckyBoard/LuckyBoardPage.tsx
  src/styles/themes/colors.ts
Labels: FEAT

#65 Feat/#64 카카오 로그인 로직 수정
  src/App.tsx
  src/apis/auth.ts
  src/apis/axios.ts
  src/apis/index.ts
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/components/domain/landing/kakaoLogin/KakaoLogin.tsx
  src/pages/auth/Auth.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/profile/Profile.tsx
  src/router/Router.tsx
  src/services/auth.ts
  src/services/index.ts
Labels: FEAT

#68 Feat/#58 회원 탈퇴 api 연동
  public/images/landing/landing-01.png
  public/images/landing/landing-02.png
  public/images/landing/landing-03.png
  public/images/landing/landing-04.png
  public/images/landing/landing-05.png
  public/images/landing/landing-06.png
  public/images/logo-sad-blue.png
  src/components/common/buttons/svgButton/SvgButton.styled.ts
  src/components/common/buttons/svgButton/SvgButton.tsx
  src/components/common/buttons/svgButton/index.ts
  src/components/common/homeButton/HomeButton.styled.ts
  src/components/common/homeButton/HomeButton.tsx
  src/components/common/homeButton/index.ts
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/components/common/modal/baseModal/BaseModal.styled.ts
  src/components/common/modal/baseModal/BaseModal.tsx
  src/components/domain/index.ts
  src/components/domain/landing/carousel/Carousel.styled.ts
  src/components/domain/landing/carousel/Carousel.tsx
  src/components/domain/landing/kakaoLogin/KakaoLogin.styled.ts
  src/components/domain/landing/kakaoLogin/KakaoLogin.tsx
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.styled.ts
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.tsx
  src/components/domain/myPage/index.ts
  src/pages/404/Error404Page.tsx
  src/pages/auth/Auth.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/profile/Profile.styled.ts
  src/pages/profile/Profile.tsx
Labels: FEAT

#67 Feat/#66 배포 세팅
  index.html
  public/favicon.ico
  public/images/logo/logo_square_180.png
  public/images/logo/logo_square_192.png
  public/images/og_image.png
  public/vite.svg
  robot.txt
  src/App.tsx
  src/components/common/buttons/index.ts
  src/components/common/index.ts
  src/components/common/modal/confirmModal/ConfirmModal.styled.ts
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/router/Router.tsx
  src/styles/themes/colors.ts
Labels: FEAT

#73 Feat/#60 럭키보드 조건부 렌더링 설정
  src/components/domain/index.ts
  src/pages/index.ts
  src/pages/luckyBoard/LuckyBoardPage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.tsx
  src/router/Router.tsx
Labels: FEAT

#75 Fix/#74 머지 후 이슈 수정하여 재커밋
  src/apis/index.ts
  src/components/common/index.ts
  src/components/common/input/Input.styled.ts
  src/components/common/input/Input.tsx
  src/components/common/input/index.ts
  src/router/Router.tsx
  src/services/index.ts
  yarn.lock
Labels: FIX

#78 럭키보드 렌더링 이슈 수정 (#77)
  .yarn/install-state.gz
  src/pages/luckyBoard/LuckyBoardPage.tsx
  yarn.lock
Labels: FIX

#84 Feat/#80 럭키보드 버튼 api연동
  src/apis/luckyday.ts
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/pages/luckyBoard/LuckyBoardPage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.tsx
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.tsx
  src/services/luckyday.ts
  src/types/domain/luckyday.ts
  src/utils/date.ts
Labels: FEAT

#85 Feat/#76 럭키보드 초기화 api 연동
  src/apis/luckyday.ts
  src/components/common/buttons/svgButton/SvgButton.tsx
  src/components/common/modal/confirmModal/ConfirmModal.tsx
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.tsx
  src/components/domain/myPage/index.ts
  src/components/domain/myPage/resetLuckyBoardModal/ResetLuckyBoardModal.styled.ts
  src/components/domain/myPage/resetLuckyBoardModal/ResetLuckyBoardModal.tsx
  src/pages/myPage/MyPage.tsx
  src/services/luckyday.ts
  src/services/users.ts
Labels: FEAT

#83 Fix/#79 배포 이슈 수정
  src/components/domain/myPage/resetLuckyBoardModal/ResetLuckyBoardModal.tsx
  src/services/luckyday.ts
  tsconfig.json
Labels: FIX

#89 Feat/#88 럭키데이 이슈 수정
  src/assets/statics/luckyday.tsx
  src/components/domain/createLuckyDay/container/calendar/Calendar.tsx
  src/components/domain/createLuckyDay/container/calendar/hooks/useCalendar.ts
  src/components/domain/createLuckyDay/selectCount/SelectCount.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.tsx
Labels: FEAT

#93 Fix/#79 배포 이슈 수정
  index.html
  vercel.json
Labels: FIX

#94 Fix/#79 배포 이슈 수정
  vercel.json
Labels: FIX

#90 Feat/#86 럭키보드 사이클 리스트 api 연동
  src/apis/luckyday.ts
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/pages/index.ts
  src/pages/luckyDayArchive/LuckyDayArchivePage.tsx
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.styled.ts
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.tsx
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.styled.ts
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.tsx
  src/router/Router.tsx
  src/services/luckyday.ts
  src/types/domain/luckyday.ts
Labels: FEAT

#92 Feat/#72 럭키보드 after api 연동
  .yarn/install-state.gz
  public/images/face-02.png
  public/images/face-03.png
  public/images/face-04.png
  public/images/face-05.png
  public/images/face-06.png
  public/images/face-07.png
  public/images/landing/landing-01.png
  public/images/landing/landing-01.webp
  public/images/landing/landing-02.png
  public/images/landing/landing-02.webp
  public/images/landing/landing-03.png
  public/images/landing/landing-03.webp
  public/images/landing/landing-04.png
  public/images/landing/landing-04.webp
  public/images/landing/landing-05.png
  public/images/landing/landing-05.webp
  public/images/landing/landing-06.png
  public/images/landing/landing-06.webp
  src/components/common/buttons/svgButton/SvgButton.styled.ts
  src/components/common/buttons/svgButton/SvgButton.tsx
  src/components/common/modal/archiveModal/ArchiveModal.styled.ts
  src/components/common/modal/baseModal/BaseModal.styled.ts
  src/components/common/modal/confirmModal/ConfirmModal.tsx
  src/components/common/svgFrame/centeredSvgFrame/centeredSvgFrame.styled.ts
  src/components/common/svgFrame/centeredSvgFrame/centeredSvgFrame.tsx
  src/components/domain/luckyBoard/countLuckyDayModal/CountLuckyDayModal.styled.ts
  src/components/domain/luckyBoard/countLuckyDayModal/CountLuckyDayModal.tsx
  src/components/domain/luckyBoard/createAlertModal/CreateAlertModal.styled.ts
  src/components/domain/luckyBoard/createAlertModal/CreateAlertModal.tsx
  src/components/domain/luckyBoard/createLuckyDayButton/CreateLuckyDayButton.tsx
  src/components/domain/luckyBoard/index.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.styled.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.tsx
  src/services/luckyday.ts
  yarn.lock
Labels: FEAT

#96 Feat/#81 에러코드 추가
  src/apis/luckyday.ts
  src/assets/statics/luckyday.tsx
  src/components/domain/createLuckyDay/container/calendar/hooks/useCalendar.ts
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.styled.ts
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/pages/auth/Auth.tsx
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.tsx
  src/pages/myPage/MyPage.tsx
  src/router/Router.tsx
  src/router/authRoute/AuthRoute.tsx
  src/services/luckyday.ts
  src/types/domain/luckyday.ts
Labels: FEAT

#98 Feat/#95 럭키보드 d day 데이터 주입
  src/components/common/modal/confirmModal/ConfirmModal.tsx
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/types/domain/luckyday.ts
Labels: FEAT

#100 Fix/#79 배포 이슈 수정
  vercel.json
Labels: FIX

#102 Feat/#97 럭키데이 생성 애니메이션 추가
  src/components/common/layout/Layout.tsx
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/pages/index.ts
  src/pages/loading/LoadingPage.styled.ts
  src/pages/loading/LoadingPage.tsx
  src/router/Router.tsx
Labels: FEAT

#103 Feat/#61 럭키데이 기록하기/기록보기 페이지 UI 및 api 연동
  public/images/img-review.png
  src/apis/luckyday.ts
  src/components/domain/index.ts
  src/components/domain/reviewLuckyDay/fileUploader/FileUploader.styled.ts
  src/components/domain/reviewLuckyDay/fileUploader/FileUploader.tsx
  src/components/domain/reviewLuckyDay/index.ts
  src/pages/index.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  src/pages/viewLuckyDay/ViewLuckyDayPage.styled.ts
  src/pages/viewLuckyDay/ViewLuckyDayPage.tsx
  src/router/Router.tsx
  src/services/luckyday.ts
  src/types/domain/luckyday.ts
Labels: FEAT

#108 Fix/#101 이미지 webp 변환
  public/images/background.png
  public/images/background.webp
  public/images/button-long.png
  public/images/empty.png
  public/images/face-01.png
  public/images/face-01.webp
  public/images/face-02.png
  public/images/face-02.webp
  public/images/face-03.png
  public/images/face-03.webp
  public/images/face-04.png
  public/images/face-04.webp
  public/images/face-05.png
  public/images/face-05.webp
  public/images/face-06.png
  public/images/face-06.webp
  public/images/face-07.png
  public/images/face-07.webp
  public/images/img-review.png
  public/images/img-review.webp
  public/images/img_medium_beige.png
  public/images/img_medium_orange.png
  public/images/img_small_square.png
  public/images/logo-basic.png
  public/images/logo-basic.webp
  public/images/machine-empty.png
  public/images/machine-empty.webp
  public/images/machine-filled.png
  public/images/machine-filled.webp
  public/images/profile/profile-01.png
  public/images/profile/profile-01.webp
  public/images/profile/profile-02.png
  public/images/profile/profile-02.webp
  public/images/profile/profile-03.png
  public/images/profile/profile-03.webp
  public/images/profile/profile-04.png
  public/images/profile/profile-04.webp
  public/images/profile/profile-05.png
  public/images/profile/profile-05.webp
  public/images/profile/profile-06.png
  public/images/profile/profile-06.webp
  public/images/profile/profile-07.png
  public/images/profile/profile-07.webp
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/logo/Logo.styled.ts
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/domain/luckyBoard/createAlertModal/CreateAlertModal.styled.ts
  src/components/domain/luckyBoard/createAlertModal/CreateAlertModal.tsx
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/components/domain/myPage/editProfileConfirmModal/EditProfileConfirmModal.styled.ts
  src/components/domain/myPage/editProfileConfirmModal/EditProfileConfirmModal.tsx
  src/pages/loading/LoadingPage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.styled.ts
  src/pages/profile/Profile.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.styled.ts
  src/pages/viewLuckyDay/ViewLuckyDayPage.styled.ts
Labels: FIX

#107 Feat/#106 지난럭키데이 조회 데이터 수정
  src/apis/luckyday.ts
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.tsx
  src/services/luckyday.ts
  src/types/domain/luckyday.ts
Labels: FEAT

#105 Feat/#99 럭키보드 보관함 api 로직 수정
  index.html
  public/images/img_empty_longBox.png
  public/images/img_empty_longBox.webp
  public/images/img_empty_mediumBox.png
  public/images/img_empty_mediumBox.webp
  public/images/img_luckydayBg.png
  public/images/img_luckydayBg.webp
  public/images/logo-sad-blue.png
  public/images/logo-sad-blue.webp
  public/images/logo-sad.png
  public/images/logo-sad.webp
  public/images/og_image.png
  public/images/og_image.webp
  src/apis/luckyday.ts
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.tsx
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.styled.ts
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.tsx
  src/pages/404/Error404Page.styled.ts
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.styled.ts
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.tsx
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.styled.ts
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/myPage.styled.ts
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.tsx
  src/router/Router.tsx
  src/services/luckyday.ts
  src/types/domain/luckyday.ts
Labels: FEAT

#110 Style/#82 반응형 처리
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/header/Header.styled.ts
  src/components/common/toast/Toast.styled.ts
  src/components/common/toast/toastItem/ToastItem.styled.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.styled.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.styled.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.styled.ts
  src/components/domain/createLuckyDay/selectCount/SelectCount.styled.ts
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.styled.ts
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.styled.ts
  src/components/domain/landing/carousel/Carousel.styled.ts
  src/pages/landing/LandingPage.styled.ts
  src/styles/globalStyle.ts
Labels: STYLE

#113 Fix/#112-배포 이슈 수정
  src/apis/luckyday.ts
  src/services/luckyday.ts
Labels: FIX

#118 Feat/#104 이미지 리사이징 기능 추가 및 회고 페이지 수정
  src/components/domain/reviewLuckyDay/fileUploader/FileUploader.tsx
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.tsx
  src/pages/viewLuckyDay/ViewLuckyDayPage.styled.ts
  src/pages/viewLuckyDay/ViewLuckyDayPage.tsx
  src/services/luckyday.ts
  src/types/domain/luckyday.ts
Labels: FEAT

#116 Feat/#115 페이지 뒤로가기 버튼 추가
  src/components/common/layout/logo/Logo.tsx
  src/pages/404/Error404Page.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.tsx
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.tsx
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.tsx
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.tsx
  src/router/Router.tsx
Labels: FEAT

#120 Style/#82 layout 반응형 처리
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/buttonLayout/singleButtonLayout/SingleButtonLayout.styled.ts
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/pages/landing/LandingPage.styled.ts
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.tsx
Labels: STYLE

#123 Feat/#119 이미지 리사이징 기능 개발
  .yarn/install-state.gz
  package.json
  src/components/common/spinner/componentSpinner/ComponentSpinner.styled.ts
  src/components/common/spinner/componentSpinner/ComponentSpinner.tsx
  src/components/common/spinner/pageSpinner/PageSpinner.styled.ts
  src/components/common/spinner/pageSpinner/PageSpinner.tsx
  src/components/domain/reviewLuckyDay/fileUploader/FileUploader.tsx
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  yarn.lock
Labels: FEAT

#122 Feat/#121 테스트 이슈 수정
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/pages/luckyBoard/LuckyBoardPage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.tsx
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.tsx
  vite.config.ts
Labels: FEAT

#128 Feat/#126 테스트 이슈 수정
  public/images/img_small.png
  public/images/img_small_beige.png
  public/images/img_small_orange.png
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/buttonLayout/ButtonLayout.tsx
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/components/domain/createLuckyDay/container/calendar/hooks/useCalendar.ts
  src/components/domain/createLuckyDay/selectCount/SelectCount.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/pages/luckyBoard/LuckyBoardPage.tsx
Labels: FEAT

#129 Feat/#127 테스트 이슈 수정
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/pages/auth/Auth.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/profile/Profile.tsx
Labels: FEAT

#132 Fix/#131 로그인오류 수정
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/pages/landing/LandingPage.tsx
Labels: FIX

#134 Feat/#130 테스트 이슈 2차 수정
  public/images/profile/profile-07.webp
  src/components/common/layout/logo/Logo.styled.ts
  src/components/common/layout/navigationToggle/NavigationToggle.styled.ts
  src/components/common/layout/navigationToggle/NavigationToggle.tsx
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/components/domain/landing/carousel/Carousel.styled.ts
  src/components/domain/luckyBoard/createAlertModal/CreateAlertModal.styled.ts
  src/components/domain/luckyBoard/createLuckyDayButton/CreateLuckyDayButton.styled.ts
  src/components/domain/myPage/deleteUserConfirmModal/DeleteUserConfirmModal.styled.ts
  src/components/domain/myPage/editProfileConfirmModal/EditProfileConfirmModal.styled.ts
  src/pages/404/Error404Page.styled.ts
  src/pages/auth/Auth.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.styled.ts
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.tsx
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.styled.ts
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.styled.ts
  src/pages/myPage/MyPage.tsx
  src/pages/profile/Profile.styled.ts
Labels: FEAT, FIX

#135 Fix/#133 2차 이슈사항 정리
  src/components/common/layout/buttonLayout/ButtonLayout.tsx
  src/components/common/modal/archiveModal/ArchiveModal.styled.ts
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/components/domain/createLuckyDay/container/calendar/hooks/useCalendar.ts
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/components/domain/createLuckyDay/selectCount/SelectCount.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/pages/luckyBoard/LuckyBoardPage.tsx
Labels: FEAT, FIX

#137 Feat/#136 테스트 2차 이슈 추가 수정
  src/components/common/modal/archiveModal/ArchiveModal.tsx
  src/components/common/svgFrame/centeredSvgFrame/centeredSvgFrame.styled.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/components/domain/myPage/editProfileConfirmModal/EditProfileConfirmModal.tsx
  src/pages/404/Error404Page.styled.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/profile/Profile.tsx
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  src/pages/viewLuckyDay/ViewLuckyDayPage.tsx
  src/router/Router.tsx
Labels: FEAT, FIX

#143 Style/#140 보관함 리스트 및 회고 페이지 반응형 처리
  index.html
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/buttonLayout/singleButtonLayout/SingleButtonLayout.styled.ts
  src/components/common/modal/Modal.styled.ts
  src/components/common/modal/archiveModal/ArchiveModal.styled.ts
  src/components/common/modal/baseModal/BaseModal.styled.ts
  src/components/common/portal/ModalPortal.tsx
  src/pages/landing/LandingPage.styled.ts
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.styled.ts
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.tsx
  src/pages/profile/Profile.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  src/pages/viewLuckyDay/ViewLuckyDayPage.styled.ts
Labels: STYLE

#146 Style/#145 배포 시 캘린더 이슈 수정
  src/components/domain/createLuckyDay/container/calendar/Calendar.styled.ts
  src/components/domain/createLuckyDay/container/calendar/Calendar.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
Labels: STYLE

#148 Feat/#147 사용하지 않는 라이브러리 및 로그 삭제
  package.json
  src/apis/luckyday.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/contexts/UserContext.tsx
  src/hooks/useUser.ts
  src/pages/luckyDayCycleDetail/LuckyDayCycleDetailPage.tsx
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.tsx
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  src/pages/viewLuckyDay/ViewLuckyDayPage.tsx
Labels: FEAT

#150 Fix/#149 배포 이슈 수정
  src/hooks/index.ts
Labels: FIX

#152 Feat/#151 에러 처리 추가
  index.html
  src/apis/axios.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/components/domain/reviewLuckyDay/fileUploader/FileUploader.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
Labels: FEAT

#155 Style/#153 럭키데이 보관함 스크롤처리 추가
  src/pages/luckyDayCycleList/LuckyDayCycleListPage.styled.ts
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.styled.ts
Labels: STYLE

#156 Feat/#154 README 작성
  README.md
Labels: FEAT

#158 Style/#157 럭키보드 반응형 처리 수정
  README.md
  index.html
  src/components/common/layout/Layout.styled.ts
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/buttonLayout/singleButtonLayout/SingleButtonLayout.styled.ts
  src/pages/landing/LandingPage.styled.ts
Labels: STYLE

#160 Style#159 전체 반응형 수정
  src/components/common/layout/buttonLayout/ButtonLayout.styled.ts
  src/components/common/layout/buttonLayout/singleButtonLayout/SingleButtonLayout.styled.ts
  src/components/domain/landing/carousel/Carousel.styled.ts
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.styled.ts
Labels: STYLE
