Repository LuckyDay-project/LuckyDay-FE, pull requests merged in 2024-11, with the labels that each got.

#227 Fix/#226 활동선택 오류 수정
  package-lock.json
  package.json
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.tsx
  src/pages/landing/LandingPage.tsx
  yarn.lock
Labels: FIX

#228 Feat/#221 튜토리얼 세부 steps 작업
  package-lock.json
  src/components/domain/luckyBoard/archiveModal/ArchiveModal.styled.ts
  src/components/tutorial/container/logoTooltip/LogoTooltip.styled.ts
  src/components/tutorial/container/tutorialTextBox/TutorialTextBox.tsx
  src/components/tutorial/context/TutorialContext.tsx
  src/components/tutorial/hooks/index.ts
  src/components/tutorial/hooks/useTutorialStep.ts
  src/components/tutorial/index.ts
  src/components/tutorial/layout/TutorialLayout.styled.ts
  src/components/tutorial/layout/TutorialLayout.tsx
  src/components/tutorial/steps/00_welcome/Welcome.tsx
  src/components/tutorial/steps/01_createCycle/01_beforeBoard/BeforeBoard.tsx
  src/components/tutorial/steps/02_check/01_afterBoard/AfterBoard.styled.ts
  src/components/tutorial/steps/02_check/01_afterBoard/AfterBoard.tsx
  src/components/tutorial/steps/03_finish/Finish.styled.ts
  src/components/tutorial/steps/03_finish/Finish.tsx
  src/components/tutorial/steps/StepWrapper.tsx
  src/components/tutorial/steps/index.ts
  src/components/tutorial/steps/tutorialSteps.ts
  src/components/tutorial/steps/tutorialTexts.ts
  src/pages/auth/Auth.tsx
  src/pages/landing/LandingPage.tsx
  src/types/tutorial/tutorial.ts
  yarn.lock
Labels: FEAT

#229 Feat/#221 튜토리얼 steps review 파트 작업
  package.json
  public/images/tutorial_review.webp
  src/components/domain/landing/carousel/Carousel.styled.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/components/tutorial/container/backButton/BackButton.styled.ts
  src/components/tutorial/container/backButton/BackButton.tsx
  src/components/tutorial/container/index.ts
  src/components/tutorial/hooks/useTutorialStep.ts
  src/components/tutorial/layout/TutorialLayout.styled.ts
  src/components/tutorial/steps/01_createCycle/01_beforeBoard/BeforeBoard.tsx
  src/components/tutorial/steps/02_check/01_afterBoard/AfterBoard.styled.ts
  src/components/tutorial/steps/02_check/01_afterBoard/AfterBoard.tsx
  src/components/tutorial/steps/02_check/02_viewActivity/ViewActivity.styled.ts
  src/components/tutorial/steps/02_check/02_viewActivity/ViewActivity.tsx
  src/components/tutorial/steps/02_check/03_review/Review.styled.ts
  src/components/tutorial/steps/02_check/03_review/Review.tsx
  src/components/tutorial/steps/03_finish/Finish.tsx
  src/components/tutorial/steps/index.ts
  src/components/tutorial/steps/tutorialSteps.ts
  src/components/tutorial/steps/tutorialTexts.ts
  src/pages/landing/LandingPage.tsx
  src/pages/tutorial/TutorialPage.styled.ts
  src/pages/viewLuckyActivity/ViewLuckyActivityPage.tsx
  vite.config.ts
  yarn.lock
Labels: FEAT

#234 Feat/#231 튜토리얼 공지사항 추가
  src/pages/noticeDetail/NoticeDetailPage.styled.ts
  src/pages/noticeDetail/NoticeDetailPage.tsx
  src/pages/noticeList/NoticeListPage.styled.ts
  src/pages/noticeList/NoticeListPage.tsx
Labels: FEAT

#233 Refactor/#230 이미지 렌더링 최적화 및 PWA ios 설정 추가
  index.html
  public/images/background.webp
  public/images/face-01.webp
  public/images/face-02.webp
  public/images/face-03.webp
  public/images/face-04.webp
  public/images/face-05.webp
  public/images/face-06.webp
  public/images/face-07.webp
  public/images/img-review.webp
  public/images/img_luckydayBg.webp
  public/images/landing/landing-01.webp
  public/images/landing/landing-02.webp
  public/images/landing/landing-03.webp
  public/images/landing/landing-04.webp
  public/images/landing/landing-05.webp
  public/images/landing/landing-06.webp
  public/images/tutorial_review.webp
  public/manifest.json
  src/components/domain/landing/carousel/Carousel.styled.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.styled.ts
  src/components/domain/luckyBoard/luckyBalls/LuckyBalls.tsx
  src/pages/landing/LandingPage.tsx
  src/pages/luckyBoard/luckyBoardAfter/LuckyBoardAfterPage.styled.ts
  src/pages/luckyBoard/luckyBoardBefore/LuckyBoardBeforePage.styled.ts
  vite.config.ts
Labels: REFACTOR, STYLE
