Repository LuckyDay-project/LuckyDay-FE, pull requests merged in 2025-02, with the labels that each got.

#256 Feat/#255 리뷰 작성 글자 수 제한 증가
  .github/issue_template.md
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.styled.ts
  src/pages/reviewLuckyDay/ReviewLuckyDayPage.tsx
  src/pages/viewLuckyDay/ViewLuckyDayPage.styled.ts
  yarn.lock
Labels: FEAT

#257 Refactor/#249 럭키데이생성 로직 리팩토링
  public/images/img_empty_mediumBox.webp
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.styled.ts
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.styled.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/ActivityToggle.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/hooks/index.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/hooks/useCustomInput.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/hooks/useSelectActivities.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/hooks/useToggle.ts
  src/components/domain/createLuckyDay/selectActivity/hooks/index.ts
  src/components/domain/createLuckyDay/selectActivity/hooks/useSelectActivity.ts
  src/components/domain/createLuckyDay/selectCount/SelectCount.tsx
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.tsx
  src/components/tutorial/steps/01_createCycle/02_selectActivity/SelectActivity.styled.ts
  src/components/tutorial/steps/01_createCycle/02_selectActivity/SelectActivity.tsx
  src/components/tutorial/steps/01_createCycle/03_setDate/SetDate.styled.ts
  src/components/tutorial/steps/01_createCycle/04_setNumber/SetNumber.styled.ts
  src/components/tutorial/steps/01_createCycle/05_exceptDate/ExceptDate.styled.ts
  src/components/tutorial/steps/01_createCycle/createLuckyday/CreateLuckyDay.styled.ts
  src/components/tutorial/steps/01_createCycle/createLuckyday/selectActivity/SelectActivity.styled.ts
  src/components/tutorial/steps/01_createCycle/createLuckyday/selectActivity/SelectActivity.tsx
  src/components/tutorial/steps/01_createCycle/createLuckyday/selectActivity/container/activityToggle/ActivityToggle.styled.ts
  src/components/tutorial/steps/01_createCycle/createLuckyday/selectActivity/container/activityToggle/ActivityToggle.tsx
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
  src/types/domain/luckyday.ts
Labels: FEAT

#258 Refactor/#249 럭키데이생성 로직 리팩토링2
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/components/domain/createLuckyDay/selectActivity/SelectActivity.tsx
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/hooks/index.ts
  src/components/domain/createLuckyDay/selectActivity/container/activityToggle/index.ts
  src/components/domain/createLuckyDay/selectActivity/container/index.ts
  src/components/domain/createLuckyDay/selectActivity/container/selectedSingleActivity/SelectedSingleActivity.styled.ts
  src/components/domain/createLuckyDay/selectActivity/container/selectedSingleActivity/SelectedSingleActivity.tsx
  src/components/domain/createLuckyDay/selectActivity/container/selectedSingleActivity/hooks/index.ts
  src/components/domain/createLuckyDay/selectActivity/container/selectedSingleActivity/hooks/useActivityToggle.ts
  src/components/domain/createLuckyDay/selectActivity/container/selectedSingleActivity/hooks/useCustomActivityInput.ts
  src/components/domain/createLuckyDay/selectActivity/container/selectedSingleActivity/hooks/useSelectActivities.ts
  src/components/domain/createLuckyDay/selectActivity/container/selectedSingleActivity/index.ts
  src/components/domain/createLuckyDay/selectExceptDate/SelectExceptDate.tsx
  src/components/domain/createLuckyDay/selectPeriod/SelectPeriod.tsx
  src/components/tutorial/steps/01_createCycle/02_selectActivity/SelectActivity.styled.ts
  src/components/tutorial/steps/01_createCycle/03_setDate/SetDate.styled.ts
  src/components/tutorial/steps/01_createCycle/04_setNumber/SetNumber.styled.ts
  src/components/tutorial/steps/01_createCycle/05_exceptDate/ExceptDate.styled.ts
  src/components/tutorial/steps/01_createCycle/06_confirm/Confirm.styled.ts
  src/components/tutorial/steps/01_createCycle/createLuckyday/CreateLuckyDay.styled.ts
  src/components/tutorial/steps/01_createCycle/createLuckyday/selectActivity/container/activityToggle/hooks/useCustomInput.ts
  src/types/domain/luckyday.ts
Labels: FEAT, REFACTOR

#259 Fix/#249 리팩토링 이후 럭키데이 생성 오류 수정
  src/components/domain/createLuckyDay/container/createLuckyDayModal/CreateLuckyDayModal.tsx
  src/components/domain/createLuckyDay/selectActivity/hooks/useSelectActivity.ts
  src/pages/createLuckyDay/CreateLuckyDayPage.tsx
Labels: FIX
